# Generated by Django 4.2 on 2024-03-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
            ],
        ),
    ]
