# Generated by Django 4.2 on 2024-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.ManyToManyField(related_name='courses', to='course.document'),
        ),
    ]
