# Generated by Django 4.2 on 2024-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.ManyToManyField(related_name='course', to='course.document'),
        ),
    ]
