# Generated by Django 4.2 on 2024-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
